# Generated by Django 4.2.7 on 2023-11-21 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='media/')),
                ('image2', models.ImageField(upload_to='media/')),
                ('image3', models.ImageField(upload_to='media/')),
                ('image4', models.ImageField(upload_to='media/')),
                ('image5', models.ImageField(upload_to='media/')),
                ('image6', models.ImageField(upload_to='media/')),
                ('image7', models.ImageField(upload_to='media/')),
                ('image8', models.ImageField(upload_to='media/')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('time_stamp', models.DateTimeField(auto_now=True)),
                ('categorey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.categorey')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
