# Generated by Django 4.2.7 on 2023-11-25 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='rate',
            field=models.IntegerField(),
        ),
    ]
