# Generated by Django 4.2.7 on 2023-11-25 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_alter_ratings_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='rate',
            field=models.FloatField(null=True),
        ),
    ]
