# Generated by Django 4.2.7 on 2023-11-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_product_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
