# Generated by Django 4.2.7 on 2023-11-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_purchaseproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseproduct',
            name='buyer_address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseproduct',
            name='buyer_name',
            field=models.CharField(max_length=30),
        ),
    ]
