# Generated by Django 4.2.7 on 2023-11-26 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0006_alter_product_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
