# Generated by Django 4.2.7 on 2023-12-01 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0009_product_all_colors_product_all_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseproduct',
            name='size',
            field=models.CharField(default='Medium size', max_length=50),
        ),
        migrations.AlterField(
            model_name='purchaseproduct',
            name='color',
            field=models.CharField(default='Any color', max_length=50),
        ),
    ]
